//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Ef5.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__ViewCache
    {
        public string ConceptualModelContainerName { get; set; }
        public string StoreModelContainerName { get; set; }
        public string ViewDefinitions { get; set; }
        public System.DateTimeOffset LastUpdated { get; set; }
    }
}
