//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Ef5.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.PostLinks = new HashSet<PostLink>();
            this.PostLinks1 = new HashSet<PostLink>();
            this.Posts1 = new HashSet<Post>();
            this.Posts11 = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AcceptedAnswerId { get; set; }
        public Nullable<int> AnswerCount { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public Nullable<System.DateTime> CommunityOwnedDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> FavoriteCount { get; set; }
        public System.DateTime LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public string LastEditorDisplayName { get; set; }
        public Nullable<int> LastEditorUserId { get; set; }
        public Nullable<int> OwnerUserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int PostTypeId { get; set; }
        public int Score { get; set; }
        public string Tags { get; set; }
        public string Title { get; set; }
        public int ViewCount { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<PostLink> PostLinks { get; set; }
        public virtual ICollection<PostLink> PostLinks1 { get; set; }
        public virtual ICollection<Post> Posts1 { get; set; }
        public virtual Post Post1 { get; set; }
        public virtual ICollection<Post> Posts11 { get; set; }
        public virtual Post Post2 { get; set; }
        public virtual PostType PostType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
