//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Ef6.Infrastructure.DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StackOverflow2010Entities : DbContext
    {
        public StackOverflow2010Entities(System.Data.Common.DbConnection dbConnection, bool contextOwnsConnection) 
            : base(dbConnection, contextOwnsConnection)
        {
        }
    
        public StackOverflow2010Entities()
            : base("name=StackOverflow2010Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Badge> Badges { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<LinkType> LinkTypes { get; set; }
        public virtual DbSet<PostLink> PostLinks { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostType> PostTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<VoteType> VoteTypes { get; set; }
    
        [DbFunction("StackOverflow2010Entities", "GetDelimitedStringValues")]
        public virtual IQueryable<string> GetDelimitedStringValues(string valuesString)
        {
            var valuesStringParameter = valuesString != null ?
                new ObjectParameter("ValuesString", valuesString) :
                new ObjectParameter("ValuesString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[StackOverflow2010Entities].[GetDelimitedStringValues](@ValuesString)", valuesStringParameter);
        }
    
        public virtual ObjectResult<PostType> GetDictionaries()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostType>("GetDictionaries");
        }
    
        public virtual ObjectResult<PostType> GetDictionaries(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PostType>("GetDictionaries", mergeOption);
        }
    
        public virtual ObjectResult<GetUserByReputationWithLastPost_Result> GetUserByReputationWithLastPost(Nullable<int> minReputation)
        {
            var minReputationParameter = minReputation.HasValue ?
                new ObjectParameter("MinReputation", minReputation) :
                new ObjectParameter("MinReputation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserByReputationWithLastPost_Result>("GetUserByReputationWithLastPost", minReputationParameter);
        }
    }
}
