//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training.Ef6.Infrastructure.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLink
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int PostId { get; set; }
        public int RelatedPostId { get; set; }
        public int LinkTypeId { get; set; }
    
        public virtual LinkType LinkType { get; set; }
        public virtual Post Post { get; set; }
        public virtual Post Post1 { get; set; }
    }
}
